### ISSUE TITLE
一排多个条目

### ISSUE THREAD

**Issue by tommyjiang** [TankNee/hexo-douban-card#10]
不太懂前端，想问下这个如何实现，比如一排三本书，现在居中一本两边有些空，非常感谢。

**Comment by TankNee** [comment]
现在没有一排多个本书的样式，如果要做的话可以在外面加个div，然后设置flex布局，调整一下每一个的大小和边距。

**Comment by tommyjiang** [comment]
好的哈，我学习一下，不太懂 flex，多谢。
