### ISSUE TITLE
添加状态按钮

### ISSUE THREAD

**Issue by webyang-male** [TankNee/hexo-douban-card#11]
例如豆瓣电影:
在看 想看 已看

**Comment by TankNee** [comment]
此类状态需要登录态的支持，但也不是不能考虑，有时间我研究一下。

**Comment by webyang-male** [comment]
thx,辛苦作者大大💗

**Comment by webyang-male** [comment]
> 此类状态需要登录态的支持，但也不是不能考虑，有时间我研究一下。

thx,辛苦作者大大💗

**Comment by junheng-wang** [comment]
问一下作者，在执行`hexo s`时出现报错：
err: Template render error: (unknown path)
是什么原因啊。。。

**Comment by TankNee** [comment]
> 问一下作者，在执行`hexo s`时出现报错： err: Template render error: (unknown path) 是什么原因啊。。。

你参考一下这个issue #3

**Comment by junheng-wang** [comment]
![image](https://user-images.githubusercontent.com/77877924/153715028-6601befe-4cc5-418d-a85a-7a5c7c5f58e8.png)
我试了一下这个，但是还是不行啊，(PS我不太懂这些博客的一些技术，就是按照网上的教程搭建的hexo博客)

**Comment by junheng-wang** [comment]
![image](https://user-images.githubusercontent.com/77877924/153715116-d96d9f16-13fa-4d5d-bd05-e2b2441c91d1.png)
上面是我的错误截图

**Comment by TankNee** [comment]
@junheng-wang 应该是renderer的问题，要不你重新开个issue，这个issue跟你这个问题不太相关。

**Comment by TankNee** [comment]
https://user-images.githubusercontent.com/43956168/153757162-55b9491c-eb45-4d98-acf0-3a6332334058.mp4

@webyang-male 最新的 1.2.6 已经支持了读取阅读状态。

**Comment by webyang-male** [comment]
> 6aa01d025afcf2f38620c2e4518a568e.mp4 
> @webyang-male 最新的 1.2.6 已经支持了读取阅读状态。

时隔这么久,终于实现了,感谢作者大大!thx!
