### ISSUE TITLE
hexo g时报错

### ISSUE THREAD

**Issue by webyang-male** [TankNee/hexo-douban-card#14]
请问这个报错如何解决?
![image](https://user-images.githubusercontent.com/52821367/158379242-01099a54-f7b6-4a7c-a302-2a4f234b7415.png)

**Comment by TankNee** [comment]
把subject id发一下，我看看，应该是这本书没图片？

**Comment by webyang-male** [comment]
> 把subject id发一下，我看看，应该是这本书没图片？

{% douban book 11614538 %}
{% douban book 33441631 %}
{% douban book 26844847 %}
{% douban book 35175321 %}
{% douban book 6038371 %}

{% douban book 35768338 %}
{% douban book 35085910 %}
{% douban book 5362856 %}
{% douban book 26382780 %}
{% douban book 26745943 %}


{% douban book 35503091 %}
{% douban book 34846688 %}

**Comment by TankNee** [comment]
收到，我有时间测试一下。

**Comment by webyang-male** [comment]
> 收到，我有时间测试一下。

大佬有解决办法了嘛

**Comment by TankNee** [comment]
最近有点忙，下周二我看一下怎么解决。

**Comment by TankNee** [comment]
![image](https://user-images.githubusercontent.com/43956168/162140573-38e33501-5dd6-469f-a93b-685e80e76473.png)
![image](https://user-images.githubusercontent.com/43956168/162140618-6bfbd92e-e6fc-424a-9d2f-bc7d266e1009.png)
![image](https://user-images.githubusercontent.com/43956168/162140644-b82d9c21-9ddd-4ff0-88a3-67bf08e3e724.png)
![image](https://user-images.githubusercontent.com/43956168/162140683-329665dc-4bc7-4354-b104-eea81b88cbbd.png)

**Comment by TankNee** [comment]
我刚刚测试了一下，似乎都挺正常的？

**Comment by webyang-male** [comment]
> 我刚刚测试了一下，似乎都挺正常的？

thx,麻烦作者大大了,怀疑是hexo主题影响,可惜用不了这个了
