### ISSUE TITLE
请问能否增加一个影集类卡片？

### ISSUE THREAD

**Issue by noitalihinna** [TankNee/hexo-douban-card#15]
TankNeen你好，
请问能否增加一个影集类卡片？

如果是影集类页面，豆瓣上显示的是首播日期
![image](https://user-images.githubusercontent.com/32699574/161904490-3c30c138-3bcb-4179-aeaa-0ee1a738542e.png)
如果使用movie类型卡片会出现无法获取的情况
![image](https://user-images.githubusercontent.com/32699574/161904704-daa3cd29-de4c-4b9d-856d-3ce62475f291.png)
目前movieSpider爬取的是上映日期
![image](https://user-images.githubusercontent.com/32699574/161904838-6185e01c-a1d0-480f-87b6-73830a8b2bc4.png)
能否添加series卡片以及对应爬取器

**Comment by TankNee** [comment]
这个类别还是电影，我兼容一下。

**Comment by TankNee** [comment]
最新的1.2.7已经修复了这个问题，请更新一下。

**Comment by noitalihinna** [comment]
已可以正常显示，感谢
