### ISSUE TITLE
images.weserv.nl 是被douban封了，还是这个获取方法已经不行了？

### ISSUE THREAD

**Issue by appotry** [TankNee/hexo-douban-card#16]
GET https://images.weserv.nl/?url=https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2194066391.jpg net::ERR_CONNECTION_RESET

图片现在获取不到了

复现地址： [Myblog](https://blog.17lai.site/posts/cf0f47fd/#hexo-douban-card)

**Comment by appotry** [comment]
囧rz  还是说网络问题，一会儿又能获取图片了

**Comment by TankNee** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            
        
    
    
      
    
        
                    未见异常
                
                    
                            
                                
                            
                            
                                TankNee
                            
                    
                        
                            
                                    ***@***.***
                                    https://tanknee.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2022年04月29日 ***@***.***> 写道： 




GET https://images.weserv.nl/?url=https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2194066391.jpg net::ERR_CONNECTION_RESET

图片限制获取不到了

复现地址： Myblog

**Comment by TankNee** [comment]
我看的时候是可以的，应该是网络问题
