### ISSUE TITLE
[功能增强]显示图片的标签由div改为img以支持图片lazyload

### ISSUE THREAD

**Issue by appotry** [TankNee/hexo-douban-card#20]
例如这个插件 [hexo-lazyload-image](https://github.com/Troy-Yang/hexo-lazyload-image)

这样可以大大加快网页加载速度，特别是在有很多个douban card的时候

**Comment by appotry** [comment]
div标签lazyload的也不是不行，只是没有现成插件，要改豆瓣插件代码，还不如直接使用img标签，适用性更好

现在就是需要一个lazyload，那种实现方法方便就上哪一个

个人看法

**Comment by TankNee** [comment]
额，我用div主要是为了实现虚化和背景，img标签我倒是没试过。
有时间我看看。

**Comment by appotry** [comment]
外面一个div wrap 做虚化，里面使用img来方便第三方插件支持lazyload ，这样怎么样

**Comment by TankNee** [comment]
我研究研究

**Comment by appotry** [comment]
使用css渐变颜色先填充背景，图片加载之后再替换参数，这样似乎也可以实现lazyload
@TankNee 这个思路可行么？ 修改特别小
```css
background-image: linear-gradient(to right, #4cbf30 0%, #0f9d58 100%);
```

**Comment by appotry** [comment]
[hexo-lazyload-image](https://github.com/Troy-Yang/hexo-lazyload-image) 升级支持 div 的 bg-lazy  属性了

**Comment by TankNee** [comment]
#24

**Comment by TankNee** [comment]
thanks for your contribution :tada:！
