### ISSUE TITLE
douban缓存没有生效，本地缓存存在，但还是访问了豆瓣网站，被提示为机器人

### ISSUE THREAD

**Issue by appotry** [TankNee/hexo-douban-card#21]
```
…你访问豆瓣的方式有点像机器人程序。为了保护用户的数据，请向我们证明你是人类:
```

如上，缓存似乎有bug

**Comment by TankNee** [comment]
奇怪，怎会如此，我看看是不是哪里写错了。

**Comment by appotry** [comment]
有进展没？ 

好几篇文章引用了几十个douban卡片，多次本地测试生成时发现失败。去豆瓣网站，就发现被限制了，需要输入验证码

**Comment by TankNee** [comment]
可以升级到最新版试一下了，问题应该已经修复了。
<img width="633" alt="image" src="https://user-images.githubusercontent.com/43956168/185731852-6b1fa3d4-f320-4682-af53-84ef6c30a37b.png">

**Comment by appotry** [comment]
效率太高了，大赞！
