### ISSUE TITLE
douban card 的 style css 样式单独作为外部文件引用

### ISSUE THREAD

**Issue by appotry** [TankNee/hexo-douban-card#23]
如果一个页面只有一个 douban card style放到 后面没有问题

如果一个页面很多个 douban card , style 除了第一个，都是重复的，影响css 渲染效率

更好的方式是css加到head头部。可以加一个配置开关，style 用户自己配置，或者自动配置

**Comment by appotry** [comment]
修改方式为，去掉渲染模板后面style几行，style部分由用户自己添加到head里面

@TankNee  这样可以加快渲染速度，style放到body里面会阻塞渲染的，影响渲染速度

如下面这个文件
https://github.com/TankNee/hexo-douban-card/blob/master/templates/bookCard.html
```
<style>
    {{style}}
</style>
```

**Comment by TankNee** [comment]
我个人认为让用户手动把样式添加到主题文件里是违背常识的，是否有现成可用的hexo钩子，在hexo g完成之后处理生成的文件，自动插入样式。

**Comment by appotry** [comment]
现在不少主题有个 inject 功能，不知道插件能否使用，可以看一下实现方式
https://github.com/jerryc127/hexo-theme-butterfly/blob/6b7d0d980678122c4280e5a66eaa6ed702621f63/_config.yml#L857

这种js css注入说不定可以实现自动把css添加到head

TankNee ***@***.***> 于2022年8月24日周三 18:15写道：

**Comment by appotry** [comment]
https://hexo.io/api/injector
找到api文档了

**Comment by TankNee** [comment]
现已支持一次性导入css文件，https://github.com/TankNee/hexo-douban-card/blob/aed70728333165a079a231199e67477ffbe94e44/index.js#L24

**Comment by appotry** [comment]
Good Job！

TankNee ***@***.***> 于2022年8月30日周二 19:18写道：
