### ISSUE TITLE
虚化背景太小，卡片不美观

### ISSUE THREAD

**Issue by AuntYang** [TankNee/hexo-douban-card#27]
作者您好，我这个卡片虚化的背景似乎太小了，整体不太美观，我看你的demo都挺好看的，请问这种是我主题（matery）的问题吗？
![image](https://user-images.githubusercontent.com/49216233/227772703-561c5862-7768-4f07-b645-1d26d4ee7f34.png)

**Comment by TankNee** [comment]
你好，看样子是你主题有些样式影响到了卡片的样式，你看看换个主题会不会恢复正常

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："AuntYang ***@***.***&gt;;
发送时间：2023年3月26日(星期天) 晚上7:31
收件人："TankNee/hexo-douban-card" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[TankNee/hexo-douban-card] 虚化背景太小，卡片不美观 (Issue #27)
-----------------------------------

 

 
作者您好，我这个卡片虚化的背景似乎太小了，整体不太美观，我看你的demo都挺好看的，请问这种是我主题（matery）的问题吗？

**Comment by AuntYang** [comment]
> 你好，看样子是你主题d有些样式影响到了卡片的样式，你看看换个主题会不会恢复正常
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："AuntYang ***@***.***&gt;; 发送时间：2023年3月26日(星期天) 晚上7:31 收件人："TankNee/hexo-douban-card" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[TankNee/hexo-douban-card] 虚化背景太小，卡片不美观 (Issue #27) ----------------------------------- 作者您好，我这个卡片虚化的背景似乎太小了，整体不太美观，我看你的demo都挺好看的，请问这种是我主题（matery）的问题吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢您回复，我尝试了更换主题，您的项目没问题，更换主题后跟您的demo一样漂亮，我不太懂前端，您是否清楚这种问题大概是出在哪里呢？
![image](https://user-images.githubusercontent.com/49216233/227788636-3b4324de-9554-45fe-bbe8-ac2ad8666f90.png)

**Comment by AuntYang** [comment]
> > 你好，看样子是你主题d有些样式影响到了卡片的样式，你看看换个主题会不会恢复正常
> > […](#)
> > ---------- 该邮件从移动设备发送
> > --------------原始邮件-------------- 发件人："AuntYang _**@**_._**>; 发送时间：2023年3月26日(星期天) 晚上7:31 收件人："TankNee/hexo-douban-card" _**@**_.**_>; 抄送："Subscribed _**@**_._**>; 主题：[TankNee/hexo-douban-card] 虚化背景太小，卡片不美观 (Issue #27) ----------------------------------- 作者您好，我这个卡片虚化的背景似乎太小了，整体不太美观，我看你的demo都挺好看的，请问这种是我主题（matery）的问题吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> 
> 感谢您回复，我尝试了更换主题，您的项目没问题，更换主题后跟您的demo一样漂亮，我不太懂前端，您是否清楚这种问题大概是出在哪里呢？ ![image](https://user-images.githubusercontent.com/49216233/227788636-3b4324de-9554-45fe-bbe8-ac2ad8666f90.png)

您好，感谢你的项目，主题css影响了卡片，修改后显示正常了
![image](https://user-images.githubusercontent.com/49216233/227834377-eae65366-42d8-4040-a8e5-de58ab5ec62b.png)
