### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by kakarrot0109** [TankNee/hexo-douban-card#5]
TypeError:Cannot read property 'attribs' of undefined

**Comment by kakarrot-dev** [comment]
@TankNee

**Comment by TankNee** [comment]
![image](https://user-images.githubusercontent.com/43956168/100499076-af91dd80-31a1-11eb-95ff-dc59edc1b6d3.png)

**Comment by TankNee** [comment]
能否提供一下出错的豆瓣书籍id号呢？

**Comment by kakarrot-dev** [comment]
https://book.douban.com/subject/26771878/

**Comment by TankNee** [comment]
> https://book.douban.com/subject/26771878/
抱歉，我好像没办法重现你的错误。能否提供一下node，npm，hexo的版本
![image](https://user-images.githubusercontent.com/43956168/100586809-a84a0b80-332a-11eb-8802-891f95c9a34c.png)

**Comment by TankNee** [comment]
请检查你的语法是否符合Hexo的语法规范

**Comment by kakarrot-dev** [comment]
我已经删除了插件了 重现不了 感谢关注 以后整博客应该还会继续用 再说啦！

**Comment by TankNee** [comment]
> 我已经删除了插件了 重现不了 感谢关注 以后整博客应该还会继续用 再说啦！

没事，感谢反馈
